Repository NVIDIA/nim-anywhere, pull requests merged in 2024-08, with the labels that each got.

#18 Monthly Patching
  README.md
  apps/functions
  apps/llm-nim-0.sh
  apps/llm-nim-1.sh
  apps/milvus.sh
  apt.txt
  code/chain_server/chain.py
  code/chain_server/configuration.py
  code/chain_server/utils.py
  code/evaluation/.gitkeep
  code/frontend/pages/chat/style.css
  code/frontend/pages/control/style.css
  code/frontend/server.py
  code/tools/audit.sh
  code/tools/audit_venv.py
  code/tools/bump.sh
  code/upload-pdfs.ipynb
  docs/2_configuration.md.py
  docs/3.4_bumping_dependencies.md
  docs/_TOC.md
  req.filters.txt
  requirements.txt
  variables.env
Labels: maintenance

#23 update documents
  docs/0_3_0_download.md
  docs/0_3_1_configure.md
  docs/_TOC.md
  docs/_static/nvwb_left_menu.png
  docs/_static/nvwb_logs.png
  docs/_static/nvwb_mount_nim.png
Labels: documentation

#21 Add Python Linting Pipeline
  .github/workflows/ci.yml
  .vscode/settings.json
  README.md
  apps/manager.py
  code/chain_server/chain.py
  code/chain_server/configuration.py
  code/chain_server/errors.py
  code/chain_server/prompts.py
  code/chain_server/server.py
  code/frontend/configuration.py
  code/frontend/mermaid.py
  code/frontend/pages/chat/__init__.py
  code/frontend/pages/control/__init__.py
  code/frontend/server.py
  code/frontend/view.py
  code/tools/audit.sh
  code/tools/lint.sh
  docs/3.0_contributing.md
  docs/3.2_docs.md
  docs/Makefile
  docs/_HEADER.md
  docs/_SUMMARY.md
  pyproject.toml
Labels: enhancement

#30 Added deep link to workbench
  README.md
  docs/Makefile
  docs/_HEADER.md
Labels: documentation
